# Generated by Django 4.1.7 on 2023-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=100)),
                ('book_Desc', models.TextField(max_length=500)),
                ('author_name', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
