# Generated by Django 4.1.7 on 2023-03-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book_alter_customuser_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
