# Generated by Django 4.1.7 on 2023-03-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
      
        ('libraryapp', '0003_alter_customuser_mobile_alter_customuser_pincode'),
    ]

    operations = [
    ]
