# Generated by Django 4.1.7 on 2023-03-28 14:31

from django.db import migrations
import libraryapp.manager


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_alter_customuser_managers_alter_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', libraryapp.manager.UserManager()),
            ],
        ),
    ]
