# Generated by Django 4.1.7 on 2023-03-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_Desc',
            field=models.CharField(max_length=500),
        ),
    ]
