# Generated by Django 4.1.7 on 2023-03-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_merge_20230328_1931'),
        ('libraryapp', '0006_alter_book_book_desc'),
    ]

    operations = [
    ]
